### ISSUE TITLE
Make the scale ports of the copy node consistent with the scale node.

### ISSUE THREAD

**Issue by fdb** [nodebox/nodebox#381]
The scale values of the copy node are "direct" values, meaning that 2.0 will increase the next copy by 200%. 

The scale node uses values like percentages, such that a value of 200 means 200%. This makes it easier in the user interface to drag the scaling controls.

We should make the behavior of the copy node consistent with the scale node.

**Comment by stebanos** [comment]
Fixed by fcb590abba853e
