### ISSUE TITLE
Data vis tutorial not clear

### ISSUE THREAD

**Issue by ialejukebox** [nodebox/nodebox#405]
Hello. I find the tutorials in the Documentation section very helpful to get started with NodeBox.
However, I cannot find a way to make the following part work in the Data visualization tutorial:

"The idea is to generate a number of points. We will do this be using a rect node connected to a scatter node.

- Create a rect node. Set its dimensions to 500 * 500.
- Create a scatter node. Connect rect1 to Shape. Connect count2 to Amount. We now have 9 points.
- Create a string node. Connect distinct1 to it.
- Create a zipmap node. Connect string1 to Keys and scatter1 to Values.
- Create a lookup node. Connect zip_map1 to List and lookup2 to Key.

The viewer pane will reveal only the same set of points but if you switch to data view you will see that each point has multiple points behind it (at the same location)."

Here is the issue: the string node represented in the picture doesn't look like the one that is available in the software (I'm running the last version). In the end, rendering the lookup3 node won't give any result, nighter in the Viewer or in the Data panel. Because of this, I can't finish the tutorial and get the final expected result. I've tried to do it all over several times double checking every step.

Can somebody check the tutorial and make it more clear? What isn't working here?
thank you

**Comment by lievn** [comment]
Hi,

The tutorial was indeed made in an older version than the latest one. You don't need to add the string node anymore although it should not be a problem.
I've shared the example as a dropbox link ( https://www.dropbox.com/s/1nvq8cxgpgjv8kp/albums.zip?dl=0 ). I've remade it based on the tutorial and did not encounter any problems.
I hope the zip helps.
You can also find some examples on data viz (and other topics) in the examples browser under File >> Open Examples.

best regards,

**Comment by fdb** [comment]
@lievn could you also update the page?
