### ISSUE TITLE
Add native Mac fullscreen/split view support.

### ISSUE THREAD

**Issue by wakest** [nodebox/nodebox#410]

**Comment by wakest** [comment]
pretty low priority, but I just updated to El Capitan and have been really enjoying using apps fullscreen and in spit view, and and should be only a few check boxes in interface builder to add it if I am not mistaken.

**Comment by fdb** [comment]
We would love to support fullscreen view! However, NodeBox is a cross-platform application and doesn't use OS X's interface builder (NIB) files. So it isn't quite as simple, but we'll figure it out.

**Comment by fdb** [comment]
Here's the info for enabling OS X fullscreen in Java applications: https://stackoverflow.com/questions/6873568/fullscreen-feature-for-java-apps-on-osx-lion

**Comment by fdb** [comment]
I've added a fix for this — we'll release this in the next version. Thanks for the request!

**Comment by wakest** [comment]
damn your fast. thank you! I felt like sort of an jerk for even mentioning such a little thing. but it's the little things like that, that make apps extra great.
