### ISSUE TITLE
arch package

### ISSUE THREAD

**Issue by bachy** [nodebox/nodebox#412]
Hello there,
not really an issue, just to inform the community that i made a first draft of an Arch Linux package for node box.
Sources are here : https://g-u-i.me/gogs/bachir/nodebox-git
do not hesitate to test it and give me some feed backs
bach

**Comment by bachy** [comment]
here we are, nodebox package for Arch Linux is on aur : https://aur.archlinux.org/packages/nodebox-git/

**Comment by fdb** [comment]
Awesome!

I notice this version is called nodebox-git, I assume because it directly pulls from HEAD. What can I do to make a version based on the latest release? (My Arch skills are a bit rusty)

**Comment by bachy** [comment]
i made a second package called "nodebox" wich pull from the last release 3.0.44 using commit tag 579ef04883e192f85b76b532883cb135f1fb684d
this package will have to be updated manually at the next release

**Comment by fdb** [comment]
Yes, that makes sense. Thanks!
