### ISSUE TITLE
Choose installation directory

### ISSUE THREAD

**Issue by techtonik** [nodebox/nodebox#420]
How to choose installation directory for Nodebox 3.0.45? It starts copying files into `C:\Users\user\AppData\Local\NodeBox` without asking.

**Comment by techtonik** [comment]
This command does the trick:

    NodeBox-3.0.45.exe /DIR="E:\iGFX\Tools\Nodebox"

But it will be nice to have the choice through the GUI.

**Comment by fdb** [comment]
It's the first time I heard a request for this — I think nobody really cares where stuff gets installed, so I think it's not something we'd like to support through the GUI.

**Comment by techtonik** [comment]
@fdb it is the first time, because previous installers proposed to choose installation path themselves.

**Comment by fdb** [comment]
Actually, we've been using the current installer for about half a year now, without any complaints 😄

**Comment by techtonik** [comment]
Probably users are not updating their software very often. I was "using" 3.0.43 year+ ago. I don't know why I upgraded. =) #421 is a pretty big issue with new version for me.
