### ISSUE TITLE
Fail to start on 32-bit Windows

### ISSUE THREAD

**Issue by techtonik** [nodebox/nodebox#421]
![image](https://cloud.githubusercontent.com/assets/515889/15919967/fbc49e12-2e1e-11e6-9482-447743b9cb77.png)

If I run `app/nodebox.jar` it starts ok, but I am not sure that libs from `runtime` become available this way.

**Comment by fdb** [comment]
Since we mentioned it in #420 , I'm working on this! I'll probably replace the current version with a 32-bit version, since I see a number of people failing to install NodeBox.

Just out of curiosity, why are you using a 32-bit version of Windows?

**Comment by techtonik** [comment]
@fdb running `java -jar nodebox.jar` works fine, so it is just the launcher code that fails.

> Just out of curiosity, why are you using a 32-bit version of Windows?

Because it is the only licensed version I have and MS doesn't allow free upgrade to 64-bit. And it probably the last Windows that I use after I understand how can I rebind Alt-F1, Alt-F2 on Linux for my user apps.

> since I see a number of people failing to install NodeBox.

How do you see this? Are there some stats that installer sends about my system?

**Comment by fdb** [comment]
>Because it is the only licensed version I have and MS doesn't allow free upgrade to 64-bit. And it probably the last Windows that I use after I understand how can I rebind Alt-F1, Alt-F2 on Linux for my user apps.

OK, I understand

> Are there some stats that installer sends about my system?

The installer sends no data about your system at all — I just heard from people on the forums or via email.

**Comment by fdb** [comment]
Okay, I replaced the version on [the download site](https://www.nodebox.net/download/) with a 32-bit version. Could you try that one?

This is the link:

https://secure.nodebox.net/downloads/NodeBox-3.0.45.exe

**Comment by techtonik** [comment]
Yay! That works.
