### ISSUE TITLE
Installing over an existing NodeBox installation fails (Windows)

### ISSUE THREAD

**Issue by fdb** [nodebox/nodebox#435]
Installing newer versions of Windows over older installations fail to open NodeBox with the following error:
```
Failed to find library,
C:\Users\username\AppData\Local\NodeBox\runtime\bin\client\jvm.dll
```

As a workaround, removing the `C:\Users\username\AppData\Local\NodeBox` folder and re-installing cleans up the installation. This is something we should do as the first step of the install on Windows.

**Comment by enzyme69** [comment]
I uninstall the previous nodebox installation and reinstall and it fixes the problem.

**Comment by fdb** [comment]
Uninstalling NodeBox does exactly that: removing the `AppData\Local\NodeBox` folder, which contains the application.

**Comment by moltenstil** [comment]
hi. unfortunately it doesn t work for me. even if appdata is deleted the error remains.

**Comment by fdb** [comment]
There is a new installer now in NodeBox 3.0.52 that should fix the issue.
