### ISSUE TITLE
Ubuntu 18.04 Build Fail

### ISSUE THREAD

**Issue by Cordoha** [nodebox/nodebox#440]
Following the Linux instructions, using Ubuntu 18.04. This is the result:
I'm not sure how to go about installing what it is suggesting.
It built correctly in 16.04! 

ant run
Buildfile: /home/justin/Git Repos/nodebox/build.xml
  [taskdef] Could not load definitions from resource com/sun/javafx/tools/ant/antlib.xml. It could not be found.

properties:
[artifact:dependencies] Downloading: org/clojars/processing-core/org.processing.core/1.5.1/org.processing.core-1.5.1.pom from repository clojars.org at https://clojars.org/repo
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[artifact:dependencies] [WARNING] Unable to get resource 'org.clojars.processing-core:org.processing.core:pom:1.5.1' from repository clojars.org (https://clojars.org/repo): Error transferring file: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[artifact:dependencies] Downloading: org/clojars/processing-core/org.processing.core/1.5.1/org.processing.core-1.5.1.pom from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'org.clojars.processing-core:org.processing.core:pom:1.5.1' in repository central (http://repo1.maven.org/maven2)
[artifact:dependencies] Downloading: ddf/minim/ddf.minim/2.2.0/ddf.minim-2.2.0.pom from repository clojars.org at https://clojars.org/repo
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[artifact:dependencies] [WARNING] Unable to get resource 'ddf.minim:ddf.minim:pom:2.2.0' from repository clojars.org (https://clojars.org/repo): Error transferring file: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[artifact:dependencies] Downloading: ddf/minim/ddf.minim/2.2.0/ddf.minim-2.2.0.pom from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'ddf.minim:ddf.minim:pom:2.2.0' in repository central (http://repo1.maven.org/maven2)
[artifact:dependencies] Downloading: de/sojamo/oscp5/0.9.8/oscp5-0.9.8.pom from repository clojars.org at https://clojars.org/repo
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[artifact:dependencies] [WARNING] Unable to get resource 'de.sojamo:oscp5:pom:0.9.8' from repository clojars.org (https://clojars.org/repo): Error transferring file: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[artifact:dependencies] Downloading: de/sojamo/oscp5/0.9.8/oscp5-0.9.8.pom from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'de.sojamo:oscp5:pom:0.9.8' in repository central (http://repo1.maven.org/maven2)
[artifact:dependencies] Downloading: ddf/minim/ddf.minim/2.2.0/ddf.minim-2.2.0.jar from repository clojars.org at https://clojars.org/repo
[artifact:dependencies] Downloading: org/clojars/processing-core/org.processing.core/1.5.1/org.processing.core-1.5.1.jar from repository clojars.org at https://clojars.org/repo
[artifact:dependencies] Downloading: de/sojamo/oscp5/0.9.8/oscp5-0.9.8.jar from repository clojars.org at https://clojars.org/repo
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[artifact:dependencies] [WARNING] Unable to get resource 'ddf.minim:ddf.minim:jar:2.2.0' from repository clojars.org (https://clojars.org/repo): Error transferring file: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[artifact:dependencies] Downloading: ddf/minim/ddf.minim/2.2.0/ddf.minim-2.2.0.jar from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[artifact:dependencies] [WARNING] Unable to get resource 'de.sojamo:oscp5:jar:0.9.8' from repository clojars.org (https://clojars.org/repo): Error transferring file: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[artifact:dependencies] Downloading: de/sojamo/oscp5/0.9.8/oscp5-0.9.8.jar from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[artifact:dependencies] [WARNING] Unable to get resource 'org.clojars.processing-core:org.processing.core:jar:1.5.1' from repository clojars.org (https://clojars.org/repo): Error transferring file: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[artifact:dependencies] Downloading: org/clojars/processing-core/org.processing.core/1.5.1/org.processing.core-1.5.1.jar from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'de.sojamo:oscp5:jar:0.9.8' in repository central (http://repo1.maven.org/maven2)
[artifact:dependencies] [INFO] Unable to find resource 'ddf.minim:ddf.minim:jar:2.2.0' in repository central (http://repo1.maven.org/maven2)
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'org.clojars.processing-core:org.processing.core:jar:1.5.1' in repository central (http://repo1.maven.org/maven2)
[artifact:dependencies] An error has occurred while processing the Maven artifact tasks.
[artifact:dependencies]  Diagnosis:
[artifact:dependencies] 
[artifact:dependencies] Unable to resolve artifact: Missing:
[artifact:dependencies] ----------
[artifact:dependencies] 1) de.sojamo:oscp5:jar:0.9.8
[artifact:dependencies] 
[artifact:dependencies]   Try downloading the file manually from the project website.
[artifact:dependencies] 
[artifact:dependencies]   Then, install it using the command: 
[artifact:dependencies]       mvn install:install-file -DgroupId=de.sojamo -DartifactId=oscp5 -Dversion=0.9.8 -Dpackaging=jar -Dfile=/path/to/file
[artifact:dependencies] 
[artifact:dependencies]   Alternatively, if you host your own repository you can deploy the file there: 
[artifact:dependencies]       mvn deploy:deploy-file -DgroupId=de.sojamo -DartifactId=oscp5 -Dversion=0.9.8 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[artifact:dependencies] 
[artifact:dependencies]   Path to dependency: 
[artifact:dependencies]   	1) net.nodebox:nodebox:jar:3.0.44
[artifact:dependencies]   	2) de.sojamo:oscp5:jar:0.9.8
[artifact:dependencies] 
[artifact:dependencies] 2) ddf.minim:ddf.minim:jar:2.2.0
[artifact:dependencies] 
[artifact:dependencies]   Try downloading the file manually from the project website.
[artifact:dependencies] 
[artifact:dependencies]   Then, install it using the command: 
[artifact:dependencies]       mvn install:install-file -DgroupId=ddf.minim -DartifactId=ddf.minim -Dversion=2.2.0 -Dpackaging=jar -Dfile=/path/to/file
[artifact:dependencies] 
[artifact:dependencies]   Alternatively, if you host your own repository you can deploy the file there: 
[artifact:dependencies]       mvn deploy:deploy-file -DgroupId=ddf.minim -DartifactId=ddf.minim -Dversion=2.2.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[artifact:dependencies] 
[artifact:dependencies]   Path to dependency: 
[artifact:dependencies]   	1) net.nodebox:nodebox:jar:3.0.44
[artifact:dependencies]   	2) ddf.minim:ddf.minim:jar:2.2.0
[artifact:dependencies] 
[artifact:dependencies] 3) org.clojars.processing-core:org.processing.core:jar:1.5.1
[artifact:dependencies] 
[artifact:dependencies]   Try downloading the file manually from the project website.
[artifact:dependencies] 
[artifact:dependencies]   Then, install it using the command: 
[artifact:dependencies]       mvn install:install-file -DgroupId=org.clojars.processing-core -DartifactId=org.processing.core -Dversion=1.5.1 -Dpackaging=jar -Dfile=/path/to/file
[artifact:dependencies] 
[artifact:dependencies]   Alternatively, if you host your own repository you can deploy the file there: 
[artifact:dependencies]       mvn deploy:deploy-file -DgroupId=org.clojars.processing-core -DartifactId=org.processing.core -Dversion=1.5.1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[artifact:dependencies] 
[artifact:dependencies]   Path to dependency: 
[artifact:dependencies]   	1) net.nodebox:nodebox:jar:3.0.44
[artifact:dependencies]   	2) org.clojars.processing-core:org.processing.core:jar:1.5.1
[artifact:dependencies] 
[artifact:dependencies] ----------
[artifact:dependencies] 3 required artifacts are missing.
[artifact:dependencies] 
[artifact:dependencies] for artifact: 
[artifact:dependencies]   net.nodebox:nodebox:jar:3.0.44
[artifact:dependencies] 
[artifact:dependencies] from the specified remote repositories:
[artifact:dependencies]   central (http://repo1.maven.org/maven2),
[artifact:dependencies]   clojars.org (https://clojars.org/repo)
[artifact:dependencies] 
[artifact:dependencies] 

BUILD FAILED
/home/justin/Git Repos/nodebox/build.xml:84: Unable to resolve artifact: Missing:
----------
1) de.sojamo:oscp5:jar:0.9.8

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=de.sojamo -DartifactId=oscp5 -Dversion=0.9.8 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=de.sojamo -DartifactId=oscp5 -Dversion=0.9.8 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) net.nodebox:nodebox:jar:3.0.44
  	2) de.sojamo:oscp5:jar:0.9.8

2) ddf.minim:ddf.minim:jar:2.2.0

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=ddf.minim -DartifactId=ddf.minim -Dversion=2.2.0 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=ddf.minim -DartifactId=ddf.minim -Dversion=2.2.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) net.nodebox:nodebox:jar:3.0.44
  	2) ddf.minim:ddf.minim:jar:2.2.0

3) org.clojars.processing-core:org.processing.core:jar:1.5.1

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.clojars.processing-core -DartifactId=org.processing.core -Dversion=1.5.1 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.clojars.processing-core -DartifactId=org.processing.core -Dversion=1.5.1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) net.nodebox:nodebox:jar:3.0.44
  	2) org.clojars.processing-core:org.processing.core:jar:1.5.1

----------
3 required artifacts are missing.

for artifact: 
  net.nodebox:nodebox:jar:3.0.44

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  clojars.org (https://clojars.org/repo)

Total time: 1 second

**Comment by fdb** [comment]
Hi,

Maven is trying to download packages from the central repository, but it seems like the SSL connection fails somehow:

```
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

I've found a [StackOverflow thread](https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty/25188331) about this. Specifically this could help:


> I found I needed to run `update-ca-certificates -f` manually, to populate the cacerts file – Portablejim Feb 5 '15 at 6:54

Could you try that?

**Comment by Cordoha** [comment]
Ran `update-ca-certificates -f` it didn't help with building though. Still the same errors.

**Comment by Cordoha** [comment]
From the same post. I tried purging, reinstalling the ca-certificates-java. It worked!

`sudo dpkg --purge --force-depends ca-certificates-java`
`sudo apt-get install ca-certificates-java`

Thanks for the help!

**Comment by fdb** [comment]
You're welcome. Have fun with NodeBox!

**Comment by opheliagame** [comment]
I seem to be having the same problem, and the above mentioned solutions don't work for me. Maybe I am missing on the order of executing those @Cordoha

**Comment by fdb** [comment]
NodeBox's build process (Maven) was pulling from an unsecure repository, which is no longer supported. I've updated the build process to pull from Maven's secure central repository.

In short: builds on Linux should now work again. I've set up a [GitHub Action](https://github.com/nodebox/nodebox/actions) to verify this.
